name: Upload changed files to S3

on:
  push:
    branches:
      - main # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Merge ./dist into the 'gh-pages' branch (dist in this case)
      - name: update dist branch
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN_REPO }}
          PUBLISH_BRANCH: dist
          PUBLISH_DIR: ./app/dist

      # Check out the new branch
      - name: checkout dist
        uses: actions/checkout@v4
        with:
          ref: dist
          # git-restore-mtime-bare uses the ref log to find the correct timestamp
          # for each file. This requires a full git history. The default value (1)
          # creates a shallow checkout.
          fetch-depth: 0
      
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade

      - name: Sync files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # Use your S3 region here
        run: |
            aws s3 sync . s3://dp-codebase-dev/Python-CiCd-Test --exclude ".git/*" --exclude ".github/*" --exact-timestamps

